### PR TITLE
2.15 fixa mer färg diversity / bioms

### PR DESCRIPTION
**Pull request by Danilll01**
Added terrain coloring of planets based on biome noise. The color from each biome is taken from a gradient that can be customized from the inspector. Each gradient from every feature is randomized for every planet. To make the mountain's ground color match up better the ground color is taken from the original palette. 

These features have different color gradients:
- Mountains
- Forests (plains)
- Polar caps (cold areas)
- Equator (warm areas)

Customize by changing or adding gradients in each array in the planet prefab
image

Mountains with "snow" at the top
image

"Tree biomes" where forests spawn
image

Cold polar caps
image

Areas with higher temperatures around the equator
image

### CODE REVIEW

**Comment by Elin1043** [comment]
Merge in main:)

**Comment by Danilll01** [comment]
But it has no conflicts 🤔 
image

**Comment by Elin1043** [comment]
Nope, men man ska ändå merga in main när man gör en pull request. Båda jag och andra har fått problem vid en merge även om det inte var några konflikter. Så det är bara så att du kan kolla att dina saker fortfarande fungerar om main mergas:)

**Comment by Danilll01** [comment]
Done :). (Det enda som inte var inmergat va mitt uppdaterade build script.)

**Pull request merged**
