### PR TITLE
Player can now land on moons, skybox is rotating and the solar system is moved to keep player close to origo

### PR DESCRIPTION
**Pull request by Elin1043**
Did the tasks for 2.18 Förflytta månar till centrum, 3.2 Simma på månar, 1.9 rotera skybox. Then I fixed the issue with the ship shaking when the player gets to far away from origo by moving the whole solar system together with the player to make sure the player stays within a certain distance from the center.
Also fixed a bug where the moons could spin around the planet very fast at some points

### CODE REVIEW

**Comment by Turbobus** [comment]
There is something wierd going on with the planet terrain coloring of the planets when they move around normally in the system. After some testing on the main branch I could not get it to happen there so I think it must be something connected to you moving the system around. I have talked with Daniel and have let him know as it is very likely a shader problem and not you. (The main branch had other problems with terrain color).

The images shows the blue spot that is increasing and decreasing in size as the planet and you follow it. In the last image the blue spot is gone but as you move, it comes back. The spot can come up all over the planet.
image
image
image

This is the big one! Going away from the moons in the spaceship is not seemless as you very clearly see that the main planet and corresponding moons around don't stay in the same place when the transition happens. Looking at the sun, I can't see it jump so I think it is just the planet - moon system the current moon is in that is the main problem (Make sure that this is correct because I am not sure 100% that the sun don't move too).

Teleporting the system is very seamless and I was surprised at how often it happened when I first looked in the scene view.

Swiming on moons also seams to work as intended which is good.

Also merge in main again!

**Comment by Turbobus** [comment]
Something is also seriously wrong with the orbits of the moons. I saw a moon that spun really fast first do a 180 (speed was constant but it just turned to rotate in other direction) when I went away from the planet. Then I moved back to the planet and observed the moon and at first is spun like normal until it slowed downed, stopped and turned around and began spinning in the other direction.
image

When this happened where it slowly turned around, going out from the planet caused it to do a 180 again and spinn correctly. I therefore suspect the moon orbit speed/direction has something to also do with the main system turning. Like when it turns around and flips the moon starts going in the other direction.

This can be observed on all moons if you wait on the main planet some time for the solar system to turn.


Another problem found is that the skybox is not rotated correctly. Both when you transition to and from a planet there is an observable jump in the skybox which should not be there if it was rotated correctly. It should be seamless like the planets/sun was before.

**Comment by Turbobus** [comment]
I fixed the problems with the terrain color and made another small pull request for that. If that is accepted into the main branch, you can get the fix from there. 

To summarize my other points that needs to be adressed:

- [ ] Need to fix seamless transitions away from moons. Currently a big jump where different things are (Other moons and planet mainly)
- [ ] Need to fix skybox rotation correctly. Should not be any jump when you transition to/from planets
- [ ] The moon orbits currently changes direction if you wait on the planets for long enough (for the whole solar system to rotate). If you transition out when they move backwords, the moons will do a 180 and directly change direction back.
- [ ] Merge in main again (Preferably after my very small terrain fix is merged in)

**Comment by Elin1043** [comment]
I think I solved most of the problems you addressed. The only one I could not fully solve was the jump of the skybox. This is not an issue with the skybox rotation itself, the skybox looks different because the player is being moved and rotated when the solar system is reset when leaving the planet. I tried to match up the rotation that is made to the player and rotate the skybox to match it. It looks better and the skybox before and after the reset is only slightly off, but it is still a little noticeable jump. If anyone has any suggestions on how to improve it, I will gladly take them. I also looked at your suggestion of taking the rotation of the sun, but it was not so simple... and it looked worse than the solution I have now. There is probably a very accurate math way to do it but nothing that I know on top of my head. However, I do not believe it is that big of an issue that it would stop the pull request from being merged if there are no other problems.

**Comment by Turbobus** [comment]
When transitioning to a planet from space the corresponding moons around that planet does not get the correct rotation. Therefore the placement of the moons  is right but the rotation of them jumps and is incorrect. The same is true when entering moons, the other moons don't get the correct rotation.

The player still does not transition out from moon correctly. If you compare against transitioning out from planets where there is no noticeable jump in other planets/moons there is a big difference. Also if you manage to go in and out relatively fast, you could see other planets / moons teleporting. The easiest way to see that there are a noticable jump is to look at the sun when transitioning out from a moon, then you can see the sun jump/change size because the distance to it is different.

The foliage on the planets seem to not spawn in correctly. In my branch I get much more when just flying around and here I only seem to get it sometimes. I don't know if something happened when you tried to fix the spawning on the moons?

----

Regarding the skybox rotation, I do find it weird that you aren't able to match it up with the sun rotation but okay. The positioning / teleportation in space should not matter because if that where true, then you would see small "jumps" in the skybox every time you teleport the whole solar system + player to fix floating point errors. You would have also seen that much earlier when the skybox didn't rotate which weren't a problem.

There is a mismatch between the rotation of the skybox and player rotation that is causing the issue which therefore means it must be possible to fix. Do you currently know how much the player view is rotated when the transition happens? From what I can see you only take the angle between the positions which I don't think will work.

What you want to do is to get the rotational quaternion difference between the before and after rotation of the player view and then rotate the skybox by the inverse of that. Lets say the players view rotated 90* then you need to rotate the skybox by that amount and in the same direction in 3D space.

image


Something similar to this I think should work where the before and after rotation is the rotation of the player before and after the transition. All rotations are Quaternions and only the last variable is a vector.

If this does not work, change the second row to be "skyboxRotation = Quaternion.Inverse(actuallRotation) * skyboxRotVector;" and test but I don't think that will work.

**Comment by Danilll01** [comment]
Looks good. Although one thing could be improved. That is the distance needed for a player to attract to a planet. Now I feel like you need to get very close before the player changes attractor (in the images the player is still not attracted to the moon). Dont know if this is a thing that can be fixed easily or if you need to have a short distance because the moons orbit so close to each other? 
image
 
image

**Comment by Elin1043** [comment]
Here we go again. The only problem I am aware of right now is the rotation of the skybox not adjusting when the player leaves a planet, so it makes it looks like it is jumping. I tried for a good amount of time to try and make it work but I could not. Maybe I or someone else can try later on but I will leave it for now.
As for the comment about the distance for the player to become attracted to a planet, it is easily adjustable and I improved it a bit to be even easier to play around with. You basically adjust the radius of where the moons are going to spawn from the planet and then you adjust the limit for when the player enters/leaves a planet. I adjusted these a bit so hopefully that satisfies the comment.

**Comment by Turbobus** [comment]
Positions of every body now seams to be handled correctly when transitioning as there are no position jumps. This makes it much more seamless to travel than before. Good Job!!! :)

----

There still is the problem of the moon rotations not being set correctly when transitioning out from another moon. Let's say there are three moons around one planet, if the player stands on one of these moons and wait for the whole solar system to rotate, when the player leaves and looks at other moons around the same planet (the two other moons in this case), they will jump in rotation
- [ ] Finally!

----

I don't know about the foliage, I think it is best if Daniel also would look at it (as you say) but after some more testing on my branch I also seamed to get very few trees other than the starting planet I spawned at. So maybe there is not something wrong with your branch but instead the whole project?

----

I will not do it now but I can look and see if I manage to fix the skybox rotation maybe (hopes are not high but in theory it must work somehow). Rotations in 3D space is super hard and the angle + axis for rotating does not make it easier. I do however see that you have tried and that is the thing that counts :) !

---- 

I didn't look very thoroughly this time so I'm sorry if I missed something and will come with it next time. The current time is maybe not the best to sit and test everything.

**Comment by Elin1043** [comment]
Moon rotations are now fixed. The first time I fixed it so they don't jump when entering the planets, so of course it broke for when leaving the planets instead... but now both should be working.

**Comment by Turbobus** [comment]
Yep, it is irritating when something like that happens. From what I can see you have fixed the rotation issue which means I think there are nothing left to comment on.

I will try to look at the skybox rotation as stated before (later today hopefully) and make new comments if I find anything else. Good job!!!!!!

**Comment by Elin1043** [comment]
Joel will try the skybox rotations in this branch. I agree with that the positions errors do not have to be dealt with here.

**Pull request merged**
