### PR TITLE
3.3 reproduction and death

### PR DESCRIPTION
**Pull request by Danilll01**
Now creatures can reproduce if they have sufficient stats and found a partner. Creatures can also die if either food or thirst is 0. A small smoke effect is also played when a child is born. Each child also has a grow-up timer that determines how long it takes for the child to grow up.

https://user-images.githubusercontent.com/59963395/225141961-68b01275-5c85-4226-9368-6b18903a64d1.mp4

https://user-images.githubusercontent.com/59963395/225141942-67001565-8a2e-428b-a781-e7536b555849.mp4

### CODE REVIEW

**Comment by Turbobus** [comment]
Fixa så poof saken kommer upp när de dör

**Comment by Elin1043** [comment]
Can this be fixed? Multiple foxes walked way down into the water.
image

**Comment by Danilll01** [comment]
This will be fixed when we implement better pathfinding (already a userstory). Either with A* or manual pathfinding.

**Comment by Elin1043** [comment]
Sound good

**Pull request merged**
