### PR TITLE
Uppgift id 1.6 rotations

### PR DESCRIPTION
**Pull request by Elin1043**
Made planets rotate around an axis. When the player is on a planet, the solar system will rotate around that planet instead. When the player leaves the planet, the solar system will reset and the planet will start rotating. There is some lag when leaving a planet. But I am not going to fix that as it has been changed in other branches. The parameter for when the player leaves/enters a planet can be adjusted later on. I think this will work better when we have reduced lag and an atmosphere, then we can really hide the transition better.

You can sometimes notice a slight "jump" when exiting the planets. But I blame the lag... I am setting the planet's rotation to the rotation that the solar system had to make the player not be able to see the solar system resetting, but you can slightly see it anyway. Not sure what I can do about this so this is good enough for now.

### CODE REVIEW

**Comment by Turbobus** [comment]
I went away from the planet and this happened. The starting planet is completely outside of where it should be so I guess it must be some bug somewhere. I just went away from the planet and nothing else. It seems to still orbit the sun but just in the wrong orbit
image

After having restarted unity too see if there was something wrong with that I still got the bug where the planet loses the original disc format. I tested going in and out from different planets and the orbits just became a mess.
image

Changing to more planets doesn't help :(
image

The rotations work from the beginning very good and it actually looks awesome speeding up the rotation speed and see how the sun and planets rotating around the planet. When going to and from planets however it seems like it is much like before when the planet you are on gets removed from the planetary disc and things fail to rotate correctly.
image

Here I actually asume that something wrong has happened because I don't think something this broken would have passed you when testing the feature. I don't know what but it must be fixed in some way as this can not happen every time when leaving a planet. 

To end on something positive, detecting when leaving the planet and entering it again seem much improved to before. I haven't tested it to much as I have been focused on the other things but from what I have felt it fells much better and not as random as it was before.

**Comment by Elin1043** [comment]
The issues you had should now be fixed. I did not manage to get all of the bugs you mentioned but I went to great lengths to force the planets to stay in orbit and aligned in the plane. 
And just a note: When testing you might see the debug orbits break or spin around weirdly, this is not something to be concerned about since the planets don't fully follow those (I am forcing them to stay in orbit). 
image

**Comment by Turbobus** [comment]
I feel so bad right now but I bring bad news here 😢

I must say that is is much harder now when you can't look at the debug lines for knowing when they are in a plane or not but after staying on the startingplanet in the beginning for a while to see if it would have broke (don't think it did) and then moving from the planet it seems that the planet you are on is reset correctly but the other does not get the correct orbit. When allowing time to go the planets move as the orbits show by the debug lines.
image

Trying this again (and not touching the time step of the planets as I did before) resulted in the same thing happening but now only to one other planet.
image

Going to and from the wrong planet caused the other planet to also slightly change plane.
image

When trying 10 planets (to see if there is more errors) I found this moon not aligned in the disc from the beginning. Here I have not moved away from the starting planet showing that there was something wrong with the orbit from the beginning. If this worked correctly it would be a nice feature to have that all planets don't move on an exact disc but here I don't hink it is intended.
image

When moving away from the planet it is total chaos with planets not aligning to the disc :(
image

It could maybe be that the planets are not correctly aligned from the beginning (exactly) which as it turns gets magnified and then results in the result I got. I don't know but it is just an idea. Also tried restarting unity here too but it did not fix the problem.

Because it is the Kepler orbit script that is messing up all orbits, is it possible to somehow disable it and move al planets completely on our own? I don't know what would be easier since that would have to be big system rewrite but if it was done good it would maybe solve a lot of our problems.

I have one idea for a system that would completely remove the Kepler orbit scrip but would add more rotations. Here is my idea:
We know the distance from the sun to the planet and the mass of the current solar system sun (would be cool to have this be able to be a little dynamic later but don't hink about it now). We also know the gravity constant G our system uses. By using a calculator like the one found here: https://www.omnicalculator.com/physics/earth-orbit it would be possible to calculate the orbit period (how long one orbit takes). By using this it would be possible to calculate how many degrees you would have to rotate the planet around the sun every time step which in turn would look like the planet moves around in a orbit. I think that the "RotateAround" would come in handy.
image
This image shows what I mean in a simple way but we need to make sure that the math works correctly for how much it has to be rotated based on delta time.

Then when starting the system you just place the planet with that distance from the sun and starts rotating it around the sun wit the calculated angle per frame. Later when doing fake rotations I think you only need to first rotate all planets and sun around the planetary axis (the axis the planet normally rotates around with that angle speed) and then when that is finished move to rotate around the sun. Basically, two rotations for every planet every frame normally (one around it's own axis and the other being the sun/planet). When faking this would jump up to 3 rotations (move around own axis, move around sun/planet and move around the still planets rotation axis).  

This would allow for a system where you easily (If everything works out like I think) change orbit inclinations for different bodies to have a more diverse system to explore instead of always a flat disc (only modify the axis it rotates around the sun a little bit). The only negative thing is that the orbits would have to be circular but with the current system we have no time to change it so it does not matter.   

In the end, I hope this don't totally destroy you as I can understand that rotations are boring and terrible right now. If you can get our current system to work it would be awesome. My idea was more something to throw out there if it could be of help and I think it would work but I can't be 100% sure before it is tested.

Sorry for finding more errors with the rotations :(

**Comment by Elin1043** [comment]
After a lot... and a lot of commits and trial and error, and frustration... I think it is finally working!(fingers crossed)

**Comment by Turbobus** [comment]
Looks super good actually and I can't seem to find something wrong about the actual rotations!!! :)

A few minor things to point out though:

If you could change the use of "Universe.player.Planet" to "Universe.player.attractor" it would save me having merge conflicts later because I have removed the "Planet" method in PillPlayer. The only thing it did was to give the already public variable attractor which can be called directly upon instead. Therefore it is unnecessary and removed.
image

When loading into game the planet you spawn at fly away as the player is not considered to be near the planet. Therefore it does not load in the high res planet mesh and the planet is never set to be the center of the universe. I think this can be changed by increasing the range to where the switch between high/low res mesh is made.

I think there should be a little more distance between the planet orbits than there are now. If the moons of both planets where at their closest point it almost looks like they will touch which is not nice. It also looks weird having different planet orbits so close to one another since the distance from planet to planet can be smaller than moon to planet.
image

As it currently stands, all planets are in a perfect flat disc. This is good for testing but is it easily possible to have a slight inclination difference in the orbits between the planets (and same for the moons but maybe to a little larger degree)? I think this would make it look a lot better when observing other planets from the current as not all planets will be in a perfectly straight line when looking. The change would be not not always rotating planets around Vector.up when orbiting (which I think it does now) to having another axes with a small change from vertical.
image
image

These issues are smaller things that hopefully should be an quick and easy fix and overall I think that the rotations work very good now. Super job!

**Comment by Elin1043** [comment]
Modified a few things from Joel's comment:
1. Replaced usage of player.Planet with player.Attractor
2. Made the player actually become a child of the starting planet, placing the planet at Universe center
3. Adjusted distance between planets and between planets and moons
4. Added an offset to the planets and the moons so they are no longer in a perfect line. A bit harder so make sure everything is working now, but we can still see the debugs circles of the actual orbiting objects, they should be rotating at the same angle and at the same time.

**Comment by Turbobus** [comment]
When you offset the planets. Is it possible to only do it up/down from the orbit? As you can see in the image the planet is closer to the sun than normal which almost makes the farthest out moon touch the sun. 
image

It is a little hard to test the distances between planets which you should have increased according to you and the commits but with this offset I feel like if two planets gets offset towards each other, they become to close again.

After some testing this seems like a bug you get when transitioning to and from planets and don't seem to be there at start.

Also, with the moons, could the offset be a little less as I assume you don't change the offset during runtime. In this case the moon will not look like it is orbiting the planet at all because it is above the planet at all time.
image

The more I test I am unsure if all issues can be fixed so easily. When offsetting the planet, it also gets offset when it is at the center of the universe. This causes the water shader to mismatch as it expects the planet to be at the absolute center which results in the player beeing able to stand under water without the shader at one side of the planet.
image

On the other side of the planet you get the opposite problem where the player gets the underwater shader when up in the air in the spaceship.
image

Because of all these problems I think it would be better to just leave the planet offset (discard it) and just have every planet in a flat (actually working) disc. You said that changing the orbit rotation axis was not something that is easily possible either so it will have to be.

The other changes you did seems to be good so it is really to just remove the offset again or fix everything if you think it is easy. Transitioning to and from planets are really seemless which is super!

**Comment by Turbobus** [comment]
After I reverted the offset change per Elins request, the orbit seems to work correctly. 

There was however one problem that the moon orbit speed was incorrect. The outer moon orbited faster than the moons closer in which is incorrect. The moons also seem to orbit the planet a lot faster when you are first at the planet but then slows down considerably when moving away. When you then come back they don't speed up again from what I have observed. 
image

I will however accept the pull request as I think the overall feature that was to be implemented is done. The moon orbiting can be fixed in the same branch that centers moons when you are on them.

**Pull request merged**
