### PR TITLE
#2.4 visual atmosphere

### PR DESCRIPTION
**Pull request by Turbobus**
The planets now have an atmosphere. The atmospheres are randomized from 9 different possible color combinations each with a customized ambient light gradient to make the ground tinted in the atmosphere color. The atmosphere can have different thicknesses and density. This will show as thickness and atmosphere brightness. Also when the planet have no atmosphere or a thinner atmosphere than normal the ambient light will either have a no atmosphere ambient gradient completely or blend by the right amount between the color gradient and the no atmosphere gradient so the ambient color also becomes less when the atmosphere is less dense.

image
image

I have also improved player shadow with a higher resolution close to the player and made the shadow distance longer. (This helps when planet is darkened by another plant in front (solar eclipse)).

image

It is a known issue that the atmosphere sometimes blink completely white / flash bright for a split second. This is the atmosphere shader I use and I have no idea what is causing it. Some values are completely fine and others have this bug and since the values sets automatically and randomly I have no way of knowing what is good and what is bad values. If you come up with a fix I would gladly hear is as it is annoying.

### CODE REVIEW

**Comment by Manfred-Hastmark** [comment]
I think the atmospheres look really nice, however the blinking bug happens quite a lot. I think you will have to fix this bug before we can merge this pull request.

**Comment by Turbobus** [comment]
Thing is, I don't know how I should fix it. I don't know what is causing the problem more than it's the atmosphere shader (I have not written the shader myself) and from the parameters I send in they should in theory work fine with no errors as they do 99% of the time.

From my testing, some random values seems to work better than others but I see no pattern in it making it impossible to actually know what values are fine / not fine. Also the values from the planet I can only do so much about until the atmosphere just doesn't work which makes my moves limited on what I can do.

I can try and look more into it but I can not be sure that I will be able to remove it. Only if I manage to see a pattern to when it happens then it will maybe be possible. I also don't know how much time I should spend on it as there are other things that can be done as well.

**Comment by Manfred-Hastmark** [comment]
> Thing is, I don't know how I should fix it. I don't know what is causing the problem more than it's the atmosphere shader (I have not written the shader myself) and from the parameters I send in they should in theory work fine with no errors as they do 99% of the time.
> 
> From my testing, some random values seems to work better than others but I see no pattern in it making it impossible to actually know what values are fine / not fine. Also the values from the planet I can only do so much about until the atmosphere just doesn't work which makes my moves limited on what I can do.
> 
> I can try and look more into it but I can not be sure that I will be able to remove it. Only if I manage to see a pattern to when it happens then it will maybe be possible. I also don't know how much time I should spend on it as there are other things that can be done as well.

Maybe we should discuss this at the meeting today

**Comment by Turbobus** [comment]
image

Haha, I paused at the right time

**Comment by Turbobus** [comment]
I have now fixed the flashing bug after a lot of testing and looking around. The shader multiplied small values together witch became NaN and broke bloom rendering causing it to flahs. The little small black pixel was the thing causing the problem. 
image


I then decided to finally change the FOV setting so it is more manageable and not so zoomed in like it was before. This caused me to have to decrease the look angle up/down (as you now see more without having to rotate to look there). It also made me have to change the location where you sit in the spaceship to not sit too far back. This also made me realize that the windows on the ship was very not transparent in certain light conditions so I made them more transparent.
image

I then added "tonemapping" to the post processing stack. This causes the colors to become much better and not as washed out as they looked before. Together with this I also added automatic dithering to the camera to lessen the color banding that can easily happen when there is a slow color gradient like the atmosphere. Don't know how well the images will work but it is a lot better. Left side is without tonemapping and without dithering at the bottom, right side has tonemapping and dithering at the bottom.
image

After this I moved on to making the camera have a longer view distance since the sun otherwise would be culled out when at the planets far from the sun. I also made the shadow even higher quality (this time using higher resolution shadow map) which I didn't feel hit performance but it can be turned down if we think it is important (Atmospheres takes much more).
image

Then I fixed the water to work with atmospheres. You can see longer under water and the atmosphere doesn't render over the water anymore. 
image

When outside the atmosphere sphere the shader lies on, the atmosphere will now render above the water instead of the other way around.
image

Lastly I have made a much better sun material for the sun to use. It now have sunspots that move around a little and more importantly the sun actually has a temperature. Based on the temperature the color of the sun will change according to a black body. This means a cooler sun will be more red and a hotter sun will be more white/blue tinted. Right now it randomizes between 3000 and 8000 degree kelvin but this can easily be changed as we see fit. (The most yellow and most white can currently not spawn but is shows the flexability)
image

The directional light in the scene is also dependent on this sun color (temperature) which makes the ground tinted slightly in the sun color.
image

**Comment by Elin1043** [comment]
It looks really good! The only thing I would like is if these harsh lines disappear(see image). If that is something you have tried to do and could not/it is too hard to fix, then just write that and I will accept anyway.
image

**Comment by Turbobus** [comment]
I don't like them either! This is caused by the amount of sampling steps the atmosphere shader does for every pixel (Depth wise). I can increase the amount of steps very easily but more steps equals less performance. This is something we can easily change later but if you want to remove them completely you have to go from 20 steps to 500 which drops the performance on my system to around 30-40 fps (not okay). You can also change the amount of steps to 1 / reduce it to get less "rings" but then other worse artifacts come up as the image shows.
image

For a complete fix I would in reality change the shader we are using to a much better shader (which I haven't found for free and writing one myself would be a lot to understand and get to work good (not worth it)) because I think that this is not made for being inside it. If you only look from the outside it is fine but inside there are problems not only connected to the lines.

**Comment by Elin1043** [comment]
That is not worth changing then. Good job with the task!

**Pull request merged**
