### PR TITLE
Uppgift id 0.18 musik/ljudeffekter 

### PR DESCRIPTION
**Pull request by Elin1043**
Added background music for when the player is on the ship and when the player is off the ship (basically in space or on a planet). Also added a thruster sound effect for when the player accelerates the ship.
Please, no comments on that you want different background music or anything like that. There were no suggestions in the Discord channel so I looked for a while and took the ones I thought worked well. If you want to change any music or sound effects, you are welcome to do it yourself after the pull request is merged.

Btw, I tried adding footsteps to the player. The little dude barely lifts his legs, making it very difficult to check when he stops on the ground. Then I tried to add events to the animation to tell a script when to play the footstep sound, but there were so many different animations and too many footsteps in each of them so that was way too much work. Then I also thought about the players' very inhuman walking and running speeds and how footsteps would sound with that. I don't think I could match it nicely so it sounds natural when the player is that fast.

### CODE REVIEW

**Comment by Turbobus** [comment]
When the player transitions away from the planet and you try to get out, the error sound that normally should play just casts an error instead.

- [ ] Fixed!

When the game is running and you thrust with the spaceship and pause, the engine sound continues to play which sounds a bit weird. Is it possible to fade out / stop playing the engine sound when the pause menu is up?

- [ ] Looked at and tested how it feels! If it sounds better keep it that way.

When you stop pressing any buttons when you fly, the thrust sound could maybe fade a little faster. Right now there is like a 1 second delay which feels wrong since I do not thrust anything for that 1 second.

- [ ] Done!

Is it possible to find any suitable landing/takeoff sounds for when the player jumps in/out from the spaceship? It feels so quiet when you are transitioning right now.

I really liked the thrust sound actually but since I have trown away that spaceship script, the thrust sound will have to be remade with the new spaceship when that gets merged in. So maybe wait until that because I'm almost done there so you can merge it in here and fix directly.

**Comment by Elin1043** [comment]
Have fixed the stuff you mentioned and have added sound effects for landing and taking off. I did a lot of adjustments on the actual sounds themselves and I think it sounds good:)

**Comment by Turbobus** [comment]
Very nice landing / takeoff sound. Not what I had in mind at first but I think it fits in very well :). The sound could be a bit higher and easier to hear though.

Also good that you paus the thruster sound. I think it sounds much more logical now.

For the thruster fade, could you do it even faster? I still fell like it is a delay when I stop pressing any buttons untill I fell that the sound begins to fade away. 

Will have more time tomorrow but for now I t hink it is good. Also waiting on my branch but it is like I said pretty much done and justs waits a pull request to be made.

**Comment by Elin1043** [comment]
Raised the volume of the landing/takeoff and fixed an issue where the landing sound would not play if the player was thrusting just before clicking F. 

Reduced the fade duration even more. This sounds really short for me now so I really do not want to decrease it anymore.

**Comment by Turbobus** [comment]
This branch should still wait for my spaceship branch to be merged first

**Comment by Elin1043** [comment]
I have merged in everything from made. Also made some adjustments to the new changes. I can't find a nice wind sound and can't make it sound natural so maybe I will wait with it. I don't want to add a sound if I don't like it. I could try finding good wind sound later on but I think this pull request is done for now.

**Comment by Hansson00** [comment]
The music doesn't always fade all the way, instead it instantly cuts. To reproduce this bug, stay on a planet until the music gets going or is at a higher volume part of the song and the switch to the spaceship.

**Pull request merged**
