### PR TITLE
Fix volume

### PR DESCRIPTION
**Pull request by Turbobus**
Rebalanced audio in game to have a nice common level. A volume slider has been added that saves your volume setting between game sessions. This volume slider can both be found in the "main menu" and "paus menu" in game.

Added a wind noise when the player is moving. Just something to have in the background to give some feedback to the player in some way.

Have added small nice sound effects to menu buttons / planet slider / seed input. This I really like and thinks sounds fantastically :)

Added a circular transition from the main menu to the loading menu

Main menu with volume slider:
image

New paus menu:
image

Disabled LOD Group component on foliage like we said to get a much further foliage distance:
image

### CODE REVIEW

**Comment by Elin1043** [comment]
I do not think the wind sound works well. It sounds too much like the thruster sound so I though it was using the wrong sound at first. Then it instantly cuts off when you stop moving, you can hear a "click" that usually happens when a sound is cut off straight away. 

- [ ] Looked at other wind sounds and fixed cut off

I like the addition of the other sound effects, maybe I don't agree with some of the sound choices but good idea to have sounds for the different parts of the UI. But since that is just a personal opinion, it will not stop me from accepting the pull request as long as the wind sound is fixed. It just sounds too out of place right now.

**Comment by Turbobus** [comment]
I have now done some more work on this branch. The sound clipping that you heard before was not because of the wind noise itself so adding a larger fade-out delay did not help. The root cause of the problem was the "HandleAudio" class and methods that directly set the volume to 0 every time you wanted to start playing a sound clipp. This made it so when you switched direction (forward to back for example) the sound would cut to 0 in between. This also resulted in the landing / take-off sound also having clipping issues as well as just flying around in the spaceship. With modifications to the Handle audio class, this was fixed.

Then I started looking at wind noises. I looked far and wide and tested multiple sounds that still are in the files if you want to test by yourself. I found that using a higher pitch wind noise as I first thought about was not realistic at all and sounded terrible. The end wind noise has a more even wind sound than before with a slightly higher pitch than before. I think it sounds different from the thruster enough that you won't confuse them for each other. If you still want another sound, please come with some reference since wind sound the way it is in game right now. Rocket exhaust and wind noise is similar since the exhaust actually causes some wind to happen.

After I was happy there, I turned back to the main menu where I discovered that my nice new sounds for the slider sounded awful on other systems. I therefore changed the audio to sound better (have tested it on my laptop too and it sounds good there now). I also changed the volume on the seed enter text to better fit in and not be as high as before.

Then I god back to fixing sound fading. This time it was the main music in the background which had weird fading issues when switching to and from the spaceship multiple times fast. My new systems fixes this to remove the weirdness of the sound switching.

**Comment by Elin1043** [comment]
I think everything looks good! However, I still do not think the wind sound suits the game. If I were to describe it, that's the wind sound you hear if you open your driving in a car. I added another wind sound that you can have a look at. I think it sounds more natural for when someone is running.
If you think it sounds good then you can accept the pull request:)
Otherwise, maybe we can get some other people's thoughts as well?

**Comment by Danilll01** [comment]
I think it looks good now with the wind sound "wind-sound-fx-long-loop". (But lowered it a bit to not be overwhelming). Also lowered the jump sound as I felt it was very harsh. 
 
One thing I think would be nice to have is if the start menu music continued to play while you are loading the game. This would make waiting not so awkward as you at least have some music playing in the background :)

**Comment by Turbobus** [comment]
I have now modified the wind sound to what I think is acceptable. Before it had to much whine and was really inconsistent (had many fluctuations) which does not sound fitting for a person running at a constant speed. I did this by taking out the part I liked the most from the suggested audio by Elin and is there the audio comes from.

I also modified some audiolevels, the most notable being the paus menu button hover sound which I changed to be higher (to sound more like the corresponding sound in the main menu).

With this, I consider this branch done again.

----

The start menu sound can't also be played during the loading screen :(. I also thought about this before and tested loading the loading menu to exist at the same time as the main menu did. This worked but as soon as the scrips started loading (when nothing can update on the loading screen) the sound also stopped playing cutting out. Therefore I decided that the best option was to fade away the sound before the loading menu.

----

And if some of you change the audio levels by using audacity. Please do not export the sound as a mp3 file. Every time this is done compression gets added and the sound quality worsens. I have exported to "wav" and selected 32 bit floating point to minimize audio quality loss.

**Comment by Elin1043** [comment]
I think everything looks good now:)
I took a look at having the music play during the loading scene and managed to do it by not destroying the music object when new scenes are loaded. Seems to work very well!
I consider this pull request done but I will let someone else merge it as I did a change:)

**Comment by Danilll01** [comment]
The "keep playing" of music between scenes works well!

**Pull request merged**
