### PR TITLE
#3.15 biombaserad djurspawning

### PR DESCRIPTION
**Pull request by isakswe**
Animals spawn basesd on the local biome. Also added variation in the creatures on each planet (currently random 20% being removed).

Using tab you can see what biome the player is in. Chickens only spawn with 0.3 trees and temperature while wolves spawn with above 0.2 temperature. This means that there are no animals below 0.2, only wolves at 0.2-0.3, and both chickens and wolves at above 0.3 temp/trees.

The actual levels for chickens/wolves are mostly for demonstration and will probably change later.

### CODE REVIEW

**Comment by Turbobus** [comment]
Merge in main

**Comment by isakswe** [comment]
Done

**Comment by Elin1043** [comment]
The debug menu has two texts which show what biome the player is in. But they are not displaying the same biome?
image

**Comment by Elin1043** [comment]
Are you sure the chickens are spawning? I went to a place with over 0.3 on temperature and trees so they should spawn, but there are none if you look in the hierarchy.
image

**Comment by isakswe** [comment]
It works as intended but the intended random culling of some types of animals really messes with the ecology. Removed for now

**Pull request merged**
