### PR TITLE
#2.22 fixa vattnet

### PR DESCRIPTION
**Pull request by Hansson00**
# Water Overhaul
## Updates
- Normal maps.
- Specular highlights.
- Foam.
- Higher resolution / Chunked.
- Becomes darker underwater with lower light levels.

## Pictures
image

### CODE REVIEW

**Comment by Hansson00** [comment]
Hade varit najs med lite feedback på stylen. Jag har suttit för länge med detta nu...

**Comment by Hansson00** [comment]
Realized that I could do some memory optimizations, should be ready tomorrow though.

**Comment by Turbobus** [comment]
Could you also play with the sliders to maybe get the foam / white stuff to show a little more? The thing we talked about during the Monday meeting.

Also I found this. The world get darker and changes something with the terrain before actually going under the water. If this  can be done at the same time the water shader for being under water goes on it would be a lot better. Right now there is a noticeable gap between it first darkens and when I move under the water.
image
image

**Comment by Danilll01** [comment]
I would say that it looks good now except for one small bug when the player looks at the sun under the water. This could be fixed later if you find it hard to fix.
image

Don't know if you wanted to improve the water as you said at the meeting on Wednesday or if you want to do it later if you have time.   
Also, merge in main :)

**Pull request closed without merging**
