### PR TITLE
#4.10 fixa placering av rymdskepp

### PR DESCRIPTION
**Pull request by isakswe**
Improved algorithm for landing ship. Now handles bumpy terrain better without clipping into ground. Not foolproof but much better.
image
image

Changed player spawning to happen in space close to the selected planet instead of on it.

Added limitations to landing with a warning noise if the landing zone isn't up to par.

### CODE REVIEW

**Comment by Turbobus** [comment]
Also do not forget to merge in main again. It seems like it will not be a problem but it can be good to do it just in case. Also if my branch gets merged in before I think there will be conflicts in the spaceship prefab. I have moved the location where the player sits and also fixed collision like you have. Also made the ship faster so it is 100 instead of 30 like it was before.

**Comment by isakswe** [comment]
"Maybe add so that the beep doesn't play over a certain distance from the ground"
Want it to be fool-proof that the user knows the button is trying to to something but is failing.

"do not forget to merge in main again"
Done, just in case. 
"there will be conflicts"
Checked the merge and the only conflict is whether to include the audio player in the spaceship so we good.

**Comment by Danilll01** [comment]
Would you mind merging in main one last time? Think another pullrequest caused the conflict to appear again :(

**Comment by isakswe** [comment]
Done

**Pull request merged**
